// To generate Go code, from the repository root directory, run:
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative internal/protobuf/services.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/protobuf/services.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Event_EvalStartedType
	//	*Event_EvalFinishedType
	//	*Event_BuildStartedType
	//	*Event_BuildFinishedType
	//	*Event_ConfirmationSubmittedType
	//	*Event_ConfirmationCancelledType
	//	*Event_ConfirmationConfirmedType
	//	*Event_Resume_
	//	*Event_Suspend_
	//	*Event_DeploymentStartedType
	//	*Event_DeploymentFinishedType
	//	*Event_RebootRequired_
	Type          isEvent_Type `protobuf_oneof:"Type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_internal_protobuf_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetType() isEvent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Event) GetEvalStartedType() *Event_EvalStarted {
	if x != nil {
		if x, ok := x.Type.(*Event_EvalStartedType); ok {
			return x.EvalStartedType
		}
	}
	return nil
}

func (x *Event) GetEvalFinishedType() *Event_EvalFinished {
	if x != nil {
		if x, ok := x.Type.(*Event_EvalFinishedType); ok {
			return x.EvalFinishedType
		}
	}
	return nil
}

func (x *Event) GetBuildStartedType() *Event_BuildStarted {
	if x != nil {
		if x, ok := x.Type.(*Event_BuildStartedType); ok {
			return x.BuildStartedType
		}
	}
	return nil
}

func (x *Event) GetBuildFinishedType() *Event_BuildFinished {
	if x != nil {
		if x, ok := x.Type.(*Event_BuildFinishedType); ok {
			return x.BuildFinishedType
		}
	}
	return nil
}

func (x *Event) GetConfirmationSubmittedType() *Event_ConfirmationSubmitted {
	if x != nil {
		if x, ok := x.Type.(*Event_ConfirmationSubmittedType); ok {
			return x.ConfirmationSubmittedType
		}
	}
	return nil
}

func (x *Event) GetConfirmationCancelledType() *Event_ConfirmationCancelled {
	if x != nil {
		if x, ok := x.Type.(*Event_ConfirmationCancelledType); ok {
			return x.ConfirmationCancelledType
		}
	}
	return nil
}

func (x *Event) GetConfirmationConfirmedType() *Event_ConfirmationConfirmed {
	if x != nil {
		if x, ok := x.Type.(*Event_ConfirmationConfirmedType); ok {
			return x.ConfirmationConfirmedType
		}
	}
	return nil
}

func (x *Event) GetResume() *Event_Resume {
	if x != nil {
		if x, ok := x.Type.(*Event_Resume_); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *Event) GetSuspend() *Event_Suspend {
	if x != nil {
		if x, ok := x.Type.(*Event_Suspend_); ok {
			return x.Suspend
		}
	}
	return nil
}

func (x *Event) GetDeploymentStartedType() *Event_DeploymentStarted {
	if x != nil {
		if x, ok := x.Type.(*Event_DeploymentStartedType); ok {
			return x.DeploymentStartedType
		}
	}
	return nil
}

func (x *Event) GetDeploymentFinishedType() *Event_DeploymentFinished {
	if x != nil {
		if x, ok := x.Type.(*Event_DeploymentFinishedType); ok {
			return x.DeploymentFinishedType
		}
	}
	return nil
}

func (x *Event) GetRebootRequired() *Event_RebootRequired {
	if x != nil {
		if x, ok := x.Type.(*Event_RebootRequired_); ok {
			return x.RebootRequired
		}
	}
	return nil
}

type isEvent_Type interface {
	isEvent_Type()
}

type Event_EvalStartedType struct {
	EvalStartedType *Event_EvalStarted `protobuf:"bytes,1,opt,name=evalStartedType,oneof"`
}

type Event_EvalFinishedType struct {
	EvalFinishedType *Event_EvalFinished `protobuf:"bytes,2,opt,name=evalFinishedType,oneof"`
}

type Event_BuildStartedType struct {
	BuildStartedType *Event_BuildStarted `protobuf:"bytes,3,opt,name=buildStartedType,oneof"`
}

type Event_BuildFinishedType struct {
	BuildFinishedType *Event_BuildFinished `protobuf:"bytes,4,opt,name=buildFinishedType,oneof"`
}

type Event_ConfirmationSubmittedType struct {
	ConfirmationSubmittedType *Event_ConfirmationSubmitted `protobuf:"bytes,5,opt,name=confirmationSubmittedType,oneof"`
}

type Event_ConfirmationCancelledType struct {
	ConfirmationCancelledType *Event_ConfirmationCancelled `protobuf:"bytes,6,opt,name=confirmationCancelledType,oneof"`
}

type Event_ConfirmationConfirmedType struct {
	ConfirmationConfirmedType *Event_ConfirmationConfirmed `protobuf:"bytes,7,opt,name=confirmationConfirmedType,oneof"`
}

type Event_Resume_ struct {
	Resume *Event_Resume `protobuf:"bytes,8,opt,name=resume,oneof"`
}

type Event_Suspend_ struct {
	Suspend *Event_Suspend `protobuf:"bytes,9,opt,name=suspend,oneof"`
}

type Event_DeploymentStartedType struct {
	DeploymentStartedType *Event_DeploymentStarted `protobuf:"bytes,10,opt,name=deploymentStartedType,oneof"`
}

type Event_DeploymentFinishedType struct {
	DeploymentFinishedType *Event_DeploymentFinished `protobuf:"bytes,11,opt,name=deploymentFinishedType,oneof"`
}

type Event_RebootRequired_ struct {
	RebootRequired *Event_RebootRequired `protobuf:"bytes,12,opt,name=rebootRequired,oneof"`
}

func (*Event_EvalStartedType) isEvent_Type() {}

func (*Event_EvalFinishedType) isEvent_Type() {}

func (*Event_BuildStartedType) isEvent_Type() {}

func (*Event_BuildFinishedType) isEvent_Type() {}

func (*Event_ConfirmationSubmittedType) isEvent_Type() {}

func (*Event_ConfirmationCancelledType) isEvent_Type() {}

func (*Event_ConfirmationConfirmedType) isEvent_Type() {}

func (*Event_Resume_) isEvent_Type() {}

func (*Event_Suspend_) isEvent_Type() {}

func (*Event_DeploymentStartedType) isEvent_Type() {}

func (*Event_DeploymentFinishedType) isEvent_Type() {}

func (*Event_RebootRequired_) isEvent_Type() {}

type ConfirmRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GenerationUuid string                 `protobuf:"bytes,1,opt,name=generationUuid" json:"generationUuid,omitempty"`
	For            string                 `protobuf:"bytes,2,opt,name=for" json:"for,omitempty"` // possible values: "build", "deploy", "all"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_internal_protobuf_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmRequest) GetGenerationUuid() string {
	if x != nil {
		return x.GenerationUuid
	}
	return ""
}

func (x *ConfirmRequest) GetFor() string {
	if x != nil {
		return x.For
	}
	return ""
}

// We consider each created genration is legit to be deployed: hard
// reset is ensured at RepositoryStatus creation.
type Generation struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Uuid                    string                 `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	RepositoryPath          string                 `protobuf:"bytes,24,opt,name=repository_path,json=repositoryPath" json:"repository_path,omitempty"`
	RepositorySubdir        string                 `protobuf:"bytes,25,opt,name=repository_subdir,json=repositorySubdir" json:"repository_subdir,omitempty"`
	SystemAttr              string                 `protobuf:"bytes,26,opt,name=system_attr,json=systemAttr" json:"system_attr,omitempty"`
	Hostname                string                 `protobuf:"bytes,3,opt,name=hostname" json:"hostname,omitempty"`
	SelectedRemoteUrl       string                 `protobuf:"bytes,4,opt,name=selected_remote_url,json=selectedRemoteUrl" json:"selected_remote_url,omitempty"`
	SelectedRemoteName      string                 `protobuf:"bytes,5,opt,name=selected_remote_name,json=selectedRemoteName" json:"selected_remote_name,omitempty"`
	SelectedBranchName      string                 `protobuf:"bytes,6,opt,name=selected_branch_name,json=selectedBranchName" json:"selected_branch_name,omitempty"`
	SelectedCommitId        string                 `protobuf:"bytes,7,opt,name=selected_commit_id,json=selectedCommitId" json:"selected_commit_id,omitempty"`
	SelectedCommitMsg       string                 `protobuf:"bytes,8,opt,name=selected_commit_msg,json=selectedCommitMsg" json:"selected_commit_msg,omitempty"`
	SelectedBranchIsTesting *wrapperspb.BoolValue  `protobuf:"bytes,9,opt,name=selected_branch_is_testing,json=selectedBranchIsTesting" json:"selected_branch_is_testing,omitempty"`
	MainCommitId            string                 `protobuf:"bytes,10,opt,name=main_commit_id,json=mainCommitId" json:"main_commit_id,omitempty"`
	MainRemoteName          string                 `protobuf:"bytes,11,opt,name=main_remote_name,json=mainRemoteName" json:"main_remote_name,omitempty"`
	MainBranchName          string                 `protobuf:"bytes,12,opt,name=main_branch_name,json=mainBranchName" json:"main_branch_name,omitempty"`
	EvalStatus              string                 `protobuf:"bytes,13,opt,name=eval_status,json=evalStatus" json:"eval_status,omitempty"`
	EvalStartedAt           *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=eval_started_at,json=evalStartedAt" json:"eval_started_at,omitempty"`
	EvalEndedAt             *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=eval_ended_at,json=evalEndedAt" json:"eval_ended_at,omitempty"`
	EvalErr                 string                 `protobuf:"bytes,16,opt,name=eval_err,json=evalErr" json:"eval_err,omitempty"`
	OutPath                 string                 `protobuf:"bytes,17,opt,name=out_path,json=outPath" json:"out_path,omitempty"`
	DrvPath                 string                 `protobuf:"bytes,18,opt,name=drv_path,json=drvPath" json:"drv_path,omitempty"`
	MachineId               string                 `protobuf:"bytes,19,opt,name=machine_id,json=machineId" json:"machine_id,omitempty"`
	BuildStatus             string                 `protobuf:"bytes,20,opt,name=build_status,json=buildStatus" json:"build_status,omitempty"`
	BuildReason             string                 `protobuf:"bytes,27,opt,name=build_reason,json=buildReason" json:"build_reason,omitempty"`
	BuildStartedAt          *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=build_started_at,json=buildStartedAt" json:"build_started_at,omitempty"`
	BuildEndedAt            *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=build_ended_at,json=buildEndedAt" json:"build_ended_at,omitempty"`
	BuildErr                string                 `protobuf:"bytes,23,opt,name=build_err,json=buildErr" json:"build_err,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Generation) Reset() {
	*x = Generation{}
	mi := &file_internal_protobuf_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation) ProtoMessage() {}

func (x *Generation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation.ProtoReflect.Descriptor instead.
func (*Generation) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{2}
}

func (x *Generation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Generation) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *Generation) GetRepositorySubdir() string {
	if x != nil {
		return x.RepositorySubdir
	}
	return ""
}

func (x *Generation) GetSystemAttr() string {
	if x != nil {
		return x.SystemAttr
	}
	return ""
}

func (x *Generation) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Generation) GetSelectedRemoteUrl() string {
	if x != nil {
		return x.SelectedRemoteUrl
	}
	return ""
}

func (x *Generation) GetSelectedRemoteName() string {
	if x != nil {
		return x.SelectedRemoteName
	}
	return ""
}

func (x *Generation) GetSelectedBranchName() string {
	if x != nil {
		return x.SelectedBranchName
	}
	return ""
}

func (x *Generation) GetSelectedCommitId() string {
	if x != nil {
		return x.SelectedCommitId
	}
	return ""
}

func (x *Generation) GetSelectedCommitMsg() string {
	if x != nil {
		return x.SelectedCommitMsg
	}
	return ""
}

func (x *Generation) GetSelectedBranchIsTesting() *wrapperspb.BoolValue {
	if x != nil {
		return x.SelectedBranchIsTesting
	}
	return nil
}

func (x *Generation) GetMainCommitId() string {
	if x != nil {
		return x.MainCommitId
	}
	return ""
}

func (x *Generation) GetMainRemoteName() string {
	if x != nil {
		return x.MainRemoteName
	}
	return ""
}

func (x *Generation) GetMainBranchName() string {
	if x != nil {
		return x.MainBranchName
	}
	return ""
}

func (x *Generation) GetEvalStatus() string {
	if x != nil {
		return x.EvalStatus
	}
	return ""
}

func (x *Generation) GetEvalStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvalStartedAt
	}
	return nil
}

func (x *Generation) GetEvalEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvalEndedAt
	}
	return nil
}

func (x *Generation) GetEvalErr() string {
	if x != nil {
		return x.EvalErr
	}
	return ""
}

func (x *Generation) GetOutPath() string {
	if x != nil {
		return x.OutPath
	}
	return ""
}

func (x *Generation) GetDrvPath() string {
	if x != nil {
		return x.DrvPath
	}
	return ""
}

func (x *Generation) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Generation) GetBuildStatus() string {
	if x != nil {
		return x.BuildStatus
	}
	return ""
}

func (x *Generation) GetBuildReason() string {
	if x != nil {
		return x.BuildReason
	}
	return ""
}

func (x *Generation) GetBuildStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BuildStartedAt
	}
	return nil
}

func (x *Generation) GetBuildEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BuildEndedAt
	}
	return nil
}

func (x *Generation) GetBuildErr() string {
	if x != nil {
		return x.BuildErr
	}
	return ""
}

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Reason        string                 `protobuf:"bytes,10,opt,name=reason" json:"reason,omitempty"`
	Generation    *Generation            `protobuf:"bytes,2,opt,name=generation" json:"generation,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt" json:"ended_at,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg" json:"error_msg,omitempty"`
	RestartComin  *wrapperspb.BoolValue  `protobuf:"bytes,6,opt,name=restart_comin,json=restartComin" json:"restart_comin,omitempty"`
	ProfilePath   string                 `protobuf:"bytes,7,opt,name=profile_path,json=profilePath" json:"profile_path,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
	Operation     string                 `protobuf:"bytes,9,opt,name=operation" json:"operation,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_internal_protobuf_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{3}
}

func (x *Deployment) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Deployment) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Deployment) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *Deployment) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Deployment) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Deployment) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *Deployment) GetRestartComin() *wrapperspb.BoolValue {
	if x != nil {
		return x.RestartComin
	}
	return nil
}

func (x *Deployment) GetProfilePath() string {
	if x != nil {
		return x.ProfilePath
	}
	return ""
}

func (x *Deployment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Deployment) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Deployment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type State struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NeedToReboot    *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=need_to_reboot,json=needToReboot" json:"need_to_reboot,omitempty"`
	IsSuspended     *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=is_suspended,json=isSuspended" json:"is_suspended,omitempty"`
	Builder         *Builder               `protobuf:"bytes,3,opt,name=builder" json:"builder,omitempty"`
	Deployer        *Deployer              `protobuf:"bytes,4,opt,name=deployer" json:"deployer,omitempty"`
	Fetcher         *Fetcher               `protobuf:"bytes,5,opt,name=fetcher" json:"fetcher,omitempty"`
	Store           *Store                 `protobuf:"bytes,6,opt,name=store" json:"store,omitempty"`
	BuildConfirmer  *Confirmer             `protobuf:"bytes,7,opt,name=build_confirmer,json=buildConfirmer" json:"build_confirmer,omitempty"`
	DeployConfirmer *Confirmer             `protobuf:"bytes,8,opt,name=deploy_confirmer,json=deployConfirmer" json:"deploy_confirmer,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_internal_protobuf_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{4}
}

func (x *State) GetNeedToReboot() *wrapperspb.BoolValue {
	if x != nil {
		return x.NeedToReboot
	}
	return nil
}

func (x *State) GetIsSuspended() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsSuspended
	}
	return nil
}

func (x *State) GetBuilder() *Builder {
	if x != nil {
		return x.Builder
	}
	return nil
}

func (x *State) GetDeployer() *Deployer {
	if x != nil {
		return x.Deployer
	}
	return nil
}

func (x *State) GetFetcher() *Fetcher {
	if x != nil {
		return x.Fetcher
	}
	return nil
}

func (x *State) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

func (x *State) GetBuildConfirmer() *Confirmer {
	if x != nil {
		return x.BuildConfirmer
	}
	return nil
}

func (x *State) GetDeployConfirmer() *Confirmer {
	if x != nil {
		return x.DeployConfirmer
	}
	return nil
}

type Deployer struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IsDeploying        *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=is_deploying,json=isDeploying" json:"is_deploying,omitempty"`
	Deployment         *Deployment            `protobuf:"bytes,2,opt,name=deployment" json:"deployment,omitempty"`
	GenerationToDeploy *Generation            `protobuf:"bytes,3,opt,name=generation_to_deploy,json=generationToDeploy" json:"generation_to_deploy,omitempty"`
	Operation          string                 `protobuf:"bytes,6,opt,name=operation" json:"operation,omitempty"`
	PreviousDeployment *Deployment            `protobuf:"bytes,4,opt,name=previous_deployment,json=previousDeployment" json:"previous_deployment,omitempty"`
	IsSuspended        *wrapperspb.BoolValue  `protobuf:"bytes,5,opt,name=is_suspended,json=isSuspended" json:"is_suspended,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Deployer) Reset() {
	*x = Deployer{}
	mi := &file_internal_protobuf_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployer) ProtoMessage() {}

func (x *Deployer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployer.ProtoReflect.Descriptor instead.
func (*Deployer) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{5}
}

func (x *Deployer) GetIsDeploying() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsDeploying
	}
	return nil
}

func (x *Deployer) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *Deployer) GetGenerationToDeploy() *Generation {
	if x != nil {
		return x.GenerationToDeploy
	}
	return nil
}

func (x *Deployer) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Deployer) GetPreviousDeployment() *Deployment {
	if x != nil {
		return x.PreviousDeployment
	}
	return nil
}

func (x *Deployer) GetIsSuspended() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsSuspended
	}
	return nil
}

type Builder struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsEvaluating   *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=is_evaluating,json=isEvaluating" json:"is_evaluating,omitempty"`
	IsBuilding     *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=is_building,json=isBuilding" json:"is_building,omitempty"`
	Generation     *Generation            `protobuf:"bytes,3,opt,name=generation" json:"generation,omitempty"`
	GenerationUuid string                 `protobuf:"bytes,4,opt,name=generation_uuid,json=generationUuid" json:"generation_uuid,omitempty"`
	IsSuspended    *wrapperspb.BoolValue  `protobuf:"bytes,5,opt,name=is_suspended,json=isSuspended" json:"is_suspended,omitempty"`
	Hostname       string                 `protobuf:"bytes,6,opt,name=hostname" json:"hostname,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Builder) Reset() {
	*x = Builder{}
	mi := &file_internal_protobuf_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Builder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Builder) ProtoMessage() {}

func (x *Builder) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Builder.ProtoReflect.Descriptor instead.
func (*Builder) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{6}
}

func (x *Builder) GetIsEvaluating() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsEvaluating
	}
	return nil
}

func (x *Builder) GetIsBuilding() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsBuilding
	}
	return nil
}

func (x *Builder) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *Builder) GetGenerationUuid() string {
	if x != nil {
		return x.GenerationUuid
	}
	return ""
}

func (x *Builder) GetIsSuspended() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsSuspended
	}
	return nil
}

func (x *Builder) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type Confirmer struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Mode                 int64                  `protobuf:"varint,1,opt,name=mode" json:"mode,omitempty"`
	Submitted            string                 `protobuf:"bytes,2,opt,name=submitted" json:"submitted,omitempty"`
	Confirmed            string                 `protobuf:"bytes,3,opt,name=confirmed" json:"confirmed,omitempty"`
	AutoconfirmDuration  int64                  `protobuf:"varint,4,opt,name=autoconfirm_duration,json=autoconfirmDuration" json:"autoconfirm_duration,omitempty"`
	AutoconfirmStartedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=autoconfirm_started_at,json=autoconfirmStartedAt" json:"autoconfirm_started_at,omitempty"`
	AutoconfirmStarted   *wrapperspb.BoolValue  `protobuf:"bytes,6,opt,name=autoconfirm_started,json=autoconfirmStarted" json:"autoconfirm_started,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Confirmer) Reset() {
	*x = Confirmer{}
	mi := &file_internal_protobuf_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirmer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmer) ProtoMessage() {}

func (x *Confirmer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmer.ProtoReflect.Descriptor instead.
func (*Confirmer) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{7}
}

func (x *Confirmer) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Confirmer) GetSubmitted() string {
	if x != nil {
		return x.Submitted
	}
	return ""
}

func (x *Confirmer) GetConfirmed() string {
	if x != nil {
		return x.Confirmed
	}
	return ""
}

func (x *Confirmer) GetAutoconfirmDuration() int64 {
	if x != nil {
		return x.AutoconfirmDuration
	}
	return 0
}

func (x *Confirmer) GetAutoconfirmStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AutoconfirmStartedAt
	}
	return nil
}

func (x *Confirmer) GetAutoconfirmStarted() *wrapperspb.BoolValue {
	if x != nil {
		return x.AutoconfirmStarted
	}
	return nil
}

type Fetcher struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsFetching       *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=is_fetching,json=isFetching" json:"is_fetching,omitempty"`
	RepositoryStatus *RepositoryStatus      `protobuf:"bytes,2,opt,name=repository_status,json=repositoryStatus" json:"repository_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Fetcher) Reset() {
	*x = Fetcher{}
	mi := &file_internal_protobuf_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fetcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fetcher) ProtoMessage() {}

func (x *Fetcher) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fetcher.ProtoReflect.Descriptor instead.
func (*Fetcher) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{8}
}

func (x *Fetcher) GetIsFetching() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsFetching
	}
	return nil
}

func (x *Fetcher) GetRepositoryStatus() *RepositoryStatus {
	if x != nil {
		return x.RepositoryStatus
	}
	return nil
}

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CommitId      string                 `protobuf:"bytes,2,opt,name=commit_id,json=commitId" json:"commit_id,omitempty"`
	CommitMsg     string                 `protobuf:"bytes,3,opt,name=commit_msg,json=commitMsg" json:"commit_msg,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg" json:"error_msg,omitempty"`
	OnTopOf       string                 `protobuf:"bytes,5,opt,name=on_top_of,json=onTopOf" json:"on_top_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_internal_protobuf_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{9}
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *Branch) GetCommitMsg() string {
	if x != nil {
		return x.CommitMsg
	}
	return ""
}

func (x *Branch) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *Branch) GetOnTopOf() string {
	if x != nil {
		return x.OnTopOf
	}
	return ""
}

type Remote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	FetchErrorMsg string                 `protobuf:"bytes,3,opt,name=fetch_error_msg,json=fetchErrorMsg" json:"fetch_error_msg,omitempty"`
	Main          *Branch                `protobuf:"bytes,4,opt,name=main" json:"main,omitempty"`
	Testing       *Branch                `protobuf:"bytes,5,opt,name=testing" json:"testing,omitempty"`
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=fetched_at,json=fetchedAt" json:"fetched_at,omitempty"`
	Fetched       *wrapperspb.BoolValue  `protobuf:"bytes,7,opt,name=fetched" json:"fetched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Remote) Reset() {
	*x = Remote{}
	mi := &file_internal_protobuf_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remote) ProtoMessage() {}

func (x *Remote) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remote.ProtoReflect.Descriptor instead.
func (*Remote) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{10}
}

func (x *Remote) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Remote) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Remote) GetFetchErrorMsg() string {
	if x != nil {
		return x.FetchErrorMsg
	}
	return ""
}

func (x *Remote) GetMain() *Branch {
	if x != nil {
		return x.Main
	}
	return nil
}

func (x *Remote) GetTesting() *Branch {
	if x != nil {
		return x.Testing
	}
	return nil
}

func (x *Remote) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

func (x *Remote) GetFetched() *wrapperspb.BoolValue {
	if x != nil {
		return x.Fetched
	}
	return nil
}

type RepositoryStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This is the deployed Main commit ID. It is used to ensure fast forward
	SelectedCommitId        string                `protobuf:"bytes,1,opt,name=selected_commit_id,json=selectedCommitId" json:"selected_commit_id,omitempty"`
	SelectedCommitMsg       string                `protobuf:"bytes,2,opt,name=selected_commit_msg,json=selectedCommitMsg" json:"selected_commit_msg,omitempty"`
	SelectedRemoteName      string                `protobuf:"bytes,3,opt,name=selected_remote_name,json=selectedRemoteName" json:"selected_remote_name,omitempty"`
	SelectedBranchName      string                `protobuf:"bytes,4,opt,name=selected_branch_name,json=selectedBranchName" json:"selected_branch_name,omitempty"`
	SelectedBranchIsTesting *wrapperspb.BoolValue `protobuf:"bytes,5,opt,name=selected_branch_is_testing,json=selectedBranchIsTesting" json:"selected_branch_is_testing,omitempty"`
	SelectedCommitSigned    *wrapperspb.BoolValue `protobuf:"bytes,6,opt,name=selected_commit_signed,json=selectedCommitSigned" json:"selected_commit_signed,omitempty"`
	SelectedCommitSignedBy  string                `protobuf:"bytes,7,opt,name=selected_commit_signed_by,json=selectedCommitSignedBy" json:"selected_commit_signed_by,omitempty"`
	// True if public keys were available when the commit has been checked out
	SelectedCommitShouldBeSigned *wrapperspb.BoolValue `protobuf:"bytes,8,opt,name=selected_commit_should_be_signed,json=selectedCommitShouldBeSigned" json:"selected_commit_should_be_signed,omitempty"`
	MainCommitId                 string                `protobuf:"bytes,9,opt,name=main_commit_id,json=mainCommitId" json:"main_commit_id,omitempty"`
	MainRemoteName               string                `protobuf:"bytes,10,opt,name=main_remote_name,json=mainRemoteName" json:"main_remote_name,omitempty"`
	MainBranchName               string                `protobuf:"bytes,11,opt,name=main_branch_name,json=mainBranchName" json:"main_branch_name,omitempty"`
	Remotes                      []*Remote             `protobuf:"bytes,12,rep,name=remotes" json:"remotes,omitempty"`
	ErrorMsg                     string                `protobuf:"bytes,13,opt,name=error_msg,json=errorMsg" json:"error_msg,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RepositoryStatus) Reset() {
	*x = RepositoryStatus{}
	mi := &file_internal_protobuf_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryStatus) ProtoMessage() {}

func (x *RepositoryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryStatus.ProtoReflect.Descriptor instead.
func (*RepositoryStatus) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{11}
}

func (x *RepositoryStatus) GetSelectedCommitId() string {
	if x != nil {
		return x.SelectedCommitId
	}
	return ""
}

func (x *RepositoryStatus) GetSelectedCommitMsg() string {
	if x != nil {
		return x.SelectedCommitMsg
	}
	return ""
}

func (x *RepositoryStatus) GetSelectedRemoteName() string {
	if x != nil {
		return x.SelectedRemoteName
	}
	return ""
}

func (x *RepositoryStatus) GetSelectedBranchName() string {
	if x != nil {
		return x.SelectedBranchName
	}
	return ""
}

func (x *RepositoryStatus) GetSelectedBranchIsTesting() *wrapperspb.BoolValue {
	if x != nil {
		return x.SelectedBranchIsTesting
	}
	return nil
}

func (x *RepositoryStatus) GetSelectedCommitSigned() *wrapperspb.BoolValue {
	if x != nil {
		return x.SelectedCommitSigned
	}
	return nil
}

func (x *RepositoryStatus) GetSelectedCommitSignedBy() string {
	if x != nil {
		return x.SelectedCommitSignedBy
	}
	return ""
}

func (x *RepositoryStatus) GetSelectedCommitShouldBeSigned() *wrapperspb.BoolValue {
	if x != nil {
		return x.SelectedCommitShouldBeSigned
	}
	return nil
}

func (x *RepositoryStatus) GetMainCommitId() string {
	if x != nil {
		return x.MainCommitId
	}
	return ""
}

func (x *RepositoryStatus) GetMainRemoteName() string {
	if x != nil {
		return x.MainRemoteName
	}
	return ""
}

func (x *RepositoryStatus) GetMainBranchName() string {
	if x != nil {
		return x.MainBranchName
	}
	return ""
}

func (x *RepositoryStatus) GetRemotes() []*Remote {
	if x != nil {
		return x.Remotes
	}
	return nil
}

func (x *RepositoryStatus) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type Store struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Deployments      []*Deployment          `protobuf:"bytes,1,rep,name=deployments" json:"deployments,omitempty"`
	Generations      []*Generation          `protobuf:"bytes,2,rep,name=generations" json:"generations,omitempty"`
	RetentionReasons map[string]string      `protobuf:"bytes,3,rep,name=retention_reasons,json=retentionReasons" json:"retention_reasons,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_internal_protobuf_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{12}
}

func (x *Store) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *Store) GetGenerations() []*Generation {
	if x != nil {
		return x.Generations
	}
	return nil
}

func (x *Store) GetRetentionReasons() map[string]string {
	if x != nil {
		return x.RetentionReasons
	}
	return nil
}

type Event_EvalStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *Generation            `protobuf:"bytes,1,opt,name=generation" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_EvalStarted) Reset() {
	*x = Event_EvalStarted{}
	mi := &file_internal_protobuf_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_EvalStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_EvalStarted) ProtoMessage() {}

func (x *Event_EvalStarted) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_EvalStarted.ProtoReflect.Descriptor instead.
func (*Event_EvalStarted) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Event_EvalStarted) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

type Event_EvalFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *Generation            `protobuf:"bytes,1,opt,name=generation" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_EvalFinished) Reset() {
	*x = Event_EvalFinished{}
	mi := &file_internal_protobuf_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_EvalFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_EvalFinished) ProtoMessage() {}

func (x *Event_EvalFinished) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_EvalFinished.ProtoReflect.Descriptor instead.
func (*Event_EvalFinished) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Event_EvalFinished) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

type Event_BuildStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *Generation            `protobuf:"bytes,1,opt,name=generation" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_BuildStarted) Reset() {
	*x = Event_BuildStarted{}
	mi := &file_internal_protobuf_services_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_BuildStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_BuildStarted) ProtoMessage() {}

func (x *Event_BuildStarted) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_BuildStarted.ProtoReflect.Descriptor instead.
func (*Event_BuildStarted) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Event_BuildStarted) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

type Event_BuildFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *Generation            `protobuf:"bytes,1,opt,name=generation" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_BuildFinished) Reset() {
	*x = Event_BuildFinished{}
	mi := &file_internal_protobuf_services_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_BuildFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_BuildFinished) ProtoMessage() {}

func (x *Event_BuildFinished) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_BuildFinished.ProtoReflect.Descriptor instead.
func (*Event_BuildFinished) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Event_BuildFinished) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

type Event_ConfirmationSubmitted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode" json:"mode,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_ConfirmationSubmitted) Reset() {
	*x = Event_ConfirmationSubmitted{}
	mi := &file_internal_protobuf_services_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_ConfirmationSubmitted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_ConfirmationSubmitted) ProtoMessage() {}

func (x *Event_ConfirmationSubmitted) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_ConfirmationSubmitted.ProtoReflect.Descriptor instead.
func (*Event_ConfirmationSubmitted) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Event_ConfirmationSubmitted) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Event_ConfirmationSubmitted) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Event_ConfirmationCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_ConfirmationCancelled) Reset() {
	*x = Event_ConfirmationCancelled{}
	mi := &file_internal_protobuf_services_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_ConfirmationCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_ConfirmationCancelled) ProtoMessage() {}

func (x *Event_ConfirmationCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_ConfirmationCancelled.ProtoReflect.Descriptor instead.
func (*Event_ConfirmationCancelled) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Event_ConfirmationCancelled) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Event_ConfirmationConfirmed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_ConfirmationConfirmed) Reset() {
	*x = Event_ConfirmationConfirmed{}
	mi := &file_internal_protobuf_services_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_ConfirmationConfirmed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_ConfirmationConfirmed) ProtoMessage() {}

func (x *Event_ConfirmationConfirmed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_ConfirmationConfirmed.ProtoReflect.Descriptor instead.
func (*Event_ConfirmationConfirmed) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Event_ConfirmationConfirmed) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Event_ConfirmationConfirmed) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Event_Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Resume) Reset() {
	*x = Event_Resume{}
	mi := &file_internal_protobuf_services_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Resume) ProtoMessage() {}

func (x *Event_Resume) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Resume.ProtoReflect.Descriptor instead.
func (*Event_Resume) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 7}
}

type Event_Suspend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Suspend) Reset() {
	*x = Event_Suspend{}
	mi := &file_internal_protobuf_services_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Suspend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Suspend) ProtoMessage() {}

func (x *Event_Suspend) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Suspend.ProtoReflect.Descriptor instead.
func (*Event_Suspend) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 8}
}

type Event_DeploymentStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_DeploymentStarted) Reset() {
	*x = Event_DeploymentStarted{}
	mi := &file_internal_protobuf_services_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_DeploymentStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_DeploymentStarted) ProtoMessage() {}

func (x *Event_DeploymentStarted) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_DeploymentStarted.ProtoReflect.Descriptor instead.
func (*Event_DeploymentStarted) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Event_DeploymentStarted) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type Event_DeploymentFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_DeploymentFinished) Reset() {
	*x = Event_DeploymentFinished{}
	mi := &file_internal_protobuf_services_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_DeploymentFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_DeploymentFinished) ProtoMessage() {}

func (x *Event_DeploymentFinished) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_DeploymentFinished.ProtoReflect.Descriptor instead.
func (*Event_DeploymentFinished) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Event_DeploymentFinished) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type Event_RebootRequired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_RebootRequired) Reset() {
	*x = Event_RebootRequired{}
	mi := &file_internal_protobuf_services_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_RebootRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_RebootRequired) ProtoMessage() {}

func (x *Event_RebootRequired) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_RebootRequired.ProtoReflect.Descriptor instead.
func (*Event_RebootRequired) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0, 11}
}

func (x *Event_RebootRequired) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

var File_internal_protobuf_services_proto protoreflect.FileDescriptor

const file_internal_protobuf_services_proto_rawDesc = "" +
	"\n" +
	" internal/protobuf/services.proto\x12\bprotobuf\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9d\r\n" +
	"\x05Event\x12G\n" +
	"\x0fevalStartedType\x18\x01 \x01(\v2\x1b.protobuf.Event.EvalStartedH\x00R\x0fevalStartedType\x12J\n" +
	"\x10evalFinishedType\x18\x02 \x01(\v2\x1c.protobuf.Event.EvalFinishedH\x00R\x10evalFinishedType\x12J\n" +
	"\x10buildStartedType\x18\x03 \x01(\v2\x1c.protobuf.Event.BuildStartedH\x00R\x10buildStartedType\x12M\n" +
	"\x11buildFinishedType\x18\x04 \x01(\v2\x1d.protobuf.Event.BuildFinishedH\x00R\x11buildFinishedType\x12e\n" +
	"\x19confirmationSubmittedType\x18\x05 \x01(\v2%.protobuf.Event.ConfirmationSubmittedH\x00R\x19confirmationSubmittedType\x12e\n" +
	"\x19confirmationCancelledType\x18\x06 \x01(\v2%.protobuf.Event.ConfirmationCancelledH\x00R\x19confirmationCancelledType\x12e\n" +
	"\x19confirmationConfirmedType\x18\a \x01(\v2%.protobuf.Event.ConfirmationConfirmedH\x00R\x19confirmationConfirmedType\x120\n" +
	"\x06resume\x18\b \x01(\v2\x16.protobuf.Event.ResumeH\x00R\x06resume\x123\n" +
	"\asuspend\x18\t \x01(\v2\x17.protobuf.Event.SuspendH\x00R\asuspend\x12Y\n" +
	"\x15deploymentStartedType\x18\n" +
	" \x01(\v2!.protobuf.Event.DeploymentStartedH\x00R\x15deploymentStartedType\x12\\\n" +
	"\x16deploymentFinishedType\x18\v \x01(\v2\".protobuf.Event.DeploymentFinishedH\x00R\x16deploymentFinishedType\x12H\n" +
	"\x0erebootRequired\x18\f \x01(\v2\x1e.protobuf.Event.RebootRequiredH\x00R\x0erebootRequired\x1aC\n" +
	"\vEvalStarted\x124\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2\x14.protobuf.GenerationR\n" +
	"generation\x1aD\n" +
	"\fEvalFinished\x124\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2\x14.protobuf.GenerationR\n" +
	"generation\x1aD\n" +
	"\fBuildStarted\x124\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2\x14.protobuf.GenerationR\n" +
	"generation\x1aE\n" +
	"\rBuildFinished\x124\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2\x14.protobuf.GenerationR\n" +
	"generation\x1a?\n" +
	"\x15ConfirmationSubmitted\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x1a+\n" +
	"\x15ConfirmationCancelled\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x1aC\n" +
	"\x15ConfirmationConfirmed\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x1a\b\n" +
	"\x06Resume\x1a\t\n" +
	"\aSuspend\x1aI\n" +
	"\x11DeploymentStarted\x124\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x14.protobuf.DeploymentR\n" +
	"deployment\x1aJ\n" +
	"\x12DeploymentFinished\x124\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x14.protobuf.DeploymentR\n" +
	"deployment\x1aF\n" +
	"\x0eRebootRequired\x124\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x14.protobuf.DeploymentR\n" +
	"deploymentB\x06\n" +
	"\x04Type\"J\n" +
	"\x0eConfirmRequest\x12&\n" +
	"\x0egenerationUuid\x18\x01 \x01(\tR\x0egenerationUuid\x12\x10\n" +
	"\x03for\x18\x02 \x01(\tR\x03for\"\xf8\b\n" +
	"\n" +
	"Generation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12'\n" +
	"\x0frepository_path\x18\x18 \x01(\tR\x0erepositoryPath\x12+\n" +
	"\x11repository_subdir\x18\x19 \x01(\tR\x10repositorySubdir\x12\x1f\n" +
	"\vsystem_attr\x18\x1a \x01(\tR\n" +
	"systemAttr\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12.\n" +
	"\x13selected_remote_url\x18\x04 \x01(\tR\x11selectedRemoteUrl\x120\n" +
	"\x14selected_remote_name\x18\x05 \x01(\tR\x12selectedRemoteName\x120\n" +
	"\x14selected_branch_name\x18\x06 \x01(\tR\x12selectedBranchName\x12,\n" +
	"\x12selected_commit_id\x18\a \x01(\tR\x10selectedCommitId\x12.\n" +
	"\x13selected_commit_msg\x18\b \x01(\tR\x11selectedCommitMsg\x12W\n" +
	"\x1aselected_branch_is_testing\x18\t \x01(\v2\x1a.google.protobuf.BoolValueR\x17selectedBranchIsTesting\x12$\n" +
	"\x0emain_commit_id\x18\n" +
	" \x01(\tR\fmainCommitId\x12(\n" +
	"\x10main_remote_name\x18\v \x01(\tR\x0emainRemoteName\x12(\n" +
	"\x10main_branch_name\x18\f \x01(\tR\x0emainBranchName\x12\x1f\n" +
	"\veval_status\x18\r \x01(\tR\n" +
	"evalStatus\x12B\n" +
	"\x0feval_started_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\revalStartedAt\x12>\n" +
	"\reval_ended_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vevalEndedAt\x12\x19\n" +
	"\beval_err\x18\x10 \x01(\tR\aevalErr\x12\x19\n" +
	"\bout_path\x18\x11 \x01(\tR\aoutPath\x12\x19\n" +
	"\bdrv_path\x18\x12 \x01(\tR\adrvPath\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x13 \x01(\tR\tmachineId\x12!\n" +
	"\fbuild_status\x18\x14 \x01(\tR\vbuildStatus\x12!\n" +
	"\fbuild_reason\x18\x1b \x01(\tR\vbuildReason\x12D\n" +
	"\x10build_started_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\x0ebuildStartedAt\x12@\n" +
	"\x0ebuild_ended_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\fbuildEndedAt\x12\x1b\n" +
	"\tbuild_err\x18\x17 \x01(\tR\bbuildErr\"\xd2\x03\n" +
	"\n" +
	"Deployment\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\x124\n" +
	"\n" +
	"generation\x18\x02 \x01(\v2\x14.protobuf.GenerationR\n" +
	"generation\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x12?\n" +
	"\rrestart_comin\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\frestartComin\x12!\n" +
	"\fprofile_path\x18\a \x01(\tR\vprofilePath\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1c\n" +
	"\toperation\x18\t \x01(\tR\toperation\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb7\x03\n" +
	"\x05State\x12@\n" +
	"\x0eneed_to_reboot\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\fneedToReboot\x12=\n" +
	"\fis_suspended\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\visSuspended\x12+\n" +
	"\abuilder\x18\x03 \x01(\v2\x11.protobuf.BuilderR\abuilder\x12.\n" +
	"\bdeployer\x18\x04 \x01(\v2\x12.protobuf.DeployerR\bdeployer\x12+\n" +
	"\afetcher\x18\x05 \x01(\v2\x11.protobuf.FetcherR\afetcher\x12%\n" +
	"\x05store\x18\x06 \x01(\v2\x0f.protobuf.StoreR\x05store\x12<\n" +
	"\x0fbuild_confirmer\x18\a \x01(\v2\x13.protobuf.ConfirmerR\x0ebuildConfirmer\x12>\n" +
	"\x10deploy_confirmer\x18\b \x01(\v2\x13.protobuf.ConfirmerR\x0fdeployConfirmer\"\xeb\x02\n" +
	"\bDeployer\x12=\n" +
	"\fis_deploying\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\visDeploying\x124\n" +
	"\n" +
	"deployment\x18\x02 \x01(\v2\x14.protobuf.DeploymentR\n" +
	"deployment\x12F\n" +
	"\x14generation_to_deploy\x18\x03 \x01(\v2\x14.protobuf.GenerationR\x12generationToDeploy\x12\x1c\n" +
	"\toperation\x18\x06 \x01(\tR\toperation\x12E\n" +
	"\x13previous_deployment\x18\x04 \x01(\v2\x14.protobuf.DeploymentR\x12previousDeployment\x12=\n" +
	"\fis_suspended\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\visSuspended\"\xc1\x02\n" +
	"\aBuilder\x12?\n" +
	"\ris_evaluating\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\fisEvaluating\x12;\n" +
	"\vis_building\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"isBuilding\x124\n" +
	"\n" +
	"generation\x18\x03 \x01(\v2\x14.protobuf.GenerationR\n" +
	"generation\x12'\n" +
	"\x0fgeneration_uuid\x18\x04 \x01(\tR\x0egenerationUuid\x12=\n" +
	"\fis_suspended\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\visSuspended\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\"\xad\x02\n" +
	"\tConfirmer\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x03R\x04mode\x12\x1c\n" +
	"\tsubmitted\x18\x02 \x01(\tR\tsubmitted\x12\x1c\n" +
	"\tconfirmed\x18\x03 \x01(\tR\tconfirmed\x121\n" +
	"\x14autoconfirm_duration\x18\x04 \x01(\x03R\x13autoconfirmDuration\x12P\n" +
	"\x16autoconfirm_started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x14autoconfirmStartedAt\x12K\n" +
	"\x13autoconfirm_started\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\x12autoconfirmStarted\"\x8f\x01\n" +
	"\aFetcher\x12;\n" +
	"\vis_fetching\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"isFetching\x12G\n" +
	"\x11repository_status\x18\x02 \x01(\v2\x1a.protobuf.RepositoryStatusR\x10repositoryStatus\"\x91\x01\n" +
	"\x06Branch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tcommit_id\x18\x02 \x01(\tR\bcommitId\x12\x1d\n" +
	"\n" +
	"commit_msg\x18\x03 \x01(\tR\tcommitMsg\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\x12\x1a\n" +
	"\ton_top_of\x18\x05 \x01(\tR\aonTopOf\"\x99\x02\n" +
	"\x06Remote\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12&\n" +
	"\x0ffetch_error_msg\x18\x03 \x01(\tR\rfetchErrorMsg\x12$\n" +
	"\x04main\x18\x04 \x01(\v2\x10.protobuf.BranchR\x04main\x12*\n" +
	"\atesting\x18\x05 \x01(\v2\x10.protobuf.BranchR\atesting\x129\n" +
	"\n" +
	"fetched_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\x124\n" +
	"\afetched\x18\a \x01(\v2\x1a.google.protobuf.BoolValueR\afetched\"\xe1\x05\n" +
	"\x10RepositoryStatus\x12,\n" +
	"\x12selected_commit_id\x18\x01 \x01(\tR\x10selectedCommitId\x12.\n" +
	"\x13selected_commit_msg\x18\x02 \x01(\tR\x11selectedCommitMsg\x120\n" +
	"\x14selected_remote_name\x18\x03 \x01(\tR\x12selectedRemoteName\x120\n" +
	"\x14selected_branch_name\x18\x04 \x01(\tR\x12selectedBranchName\x12W\n" +
	"\x1aselected_branch_is_testing\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\x17selectedBranchIsTesting\x12P\n" +
	"\x16selected_commit_signed\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\x14selectedCommitSigned\x129\n" +
	"\x19selected_commit_signed_by\x18\a \x01(\tR\x16selectedCommitSignedBy\x12b\n" +
	" selected_commit_should_be_signed\x18\b \x01(\v2\x1a.google.protobuf.BoolValueR\x1cselectedCommitShouldBeSigned\x12$\n" +
	"\x0emain_commit_id\x18\t \x01(\tR\fmainCommitId\x12(\n" +
	"\x10main_remote_name\x18\n" +
	" \x01(\tR\x0emainRemoteName\x12(\n" +
	"\x10main_branch_name\x18\v \x01(\tR\x0emainBranchName\x12*\n" +
	"\aremotes\x18\f \x03(\v2\x10.protobuf.RemoteR\aremotes\x12\x1b\n" +
	"\terror_msg\x18\r \x01(\tR\berrorMsg\"\x90\x02\n" +
	"\x05Store\x126\n" +
	"\vdeployments\x18\x01 \x03(\v2\x14.protobuf.DeploymentR\vdeployments\x126\n" +
	"\vgenerations\x18\x02 \x03(\v2\x14.protobuf.GenerationR\vgenerations\x12R\n" +
	"\x11retention_reasons\x18\x03 \x03(\v2%.protobuf.Store.RetentionReasonsEntryR\x10retentionReasons\x1aC\n" +
	"\x15RetentionReasonsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xb2\x03\n" +
	"\x05Comin\x125\n" +
	"\bGetState\x12\x16.google.protobuf.Empty\x1a\x0f.protobuf.State\"\x00\x129\n" +
	"\x05Fetch\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12;\n" +
	"\aSuspend\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12:\n" +
	"\x06Resume\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\aConfirm\x12\x18.protobuf.ConfirmRequest\x1a\x16.google.protobuf.Empty\"\x00\x123\n" +
	"\x06Events\x12\x16.google.protobuf.Empty\x1a\x0f.protobuf.Event0\x01\x12J\n" +
	"\x16SwitchDeploymentLatest\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B/Z(github.com/nlewo/comin/internal/protobuf\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_internal_protobuf_services_proto_rawDescOnce sync.Once
	file_internal_protobuf_services_proto_rawDescData []byte
)

func file_internal_protobuf_services_proto_rawDescGZIP() []byte {
	file_internal_protobuf_services_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protobuf_services_proto_rawDesc), len(file_internal_protobuf_services_proto_rawDesc)))
	})
	return file_internal_protobuf_services_proto_rawDescData
}

var file_internal_protobuf_services_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_internal_protobuf_services_proto_goTypes = []any{
	(*Event)(nil),                       // 0: protobuf.Event
	(*ConfirmRequest)(nil),              // 1: protobuf.ConfirmRequest
	(*Generation)(nil),                  // 2: protobuf.Generation
	(*Deployment)(nil),                  // 3: protobuf.Deployment
	(*State)(nil),                       // 4: protobuf.State
	(*Deployer)(nil),                    // 5: protobuf.Deployer
	(*Builder)(nil),                     // 6: protobuf.Builder
	(*Confirmer)(nil),                   // 7: protobuf.Confirmer
	(*Fetcher)(nil),                     // 8: protobuf.Fetcher
	(*Branch)(nil),                      // 9: protobuf.Branch
	(*Remote)(nil),                      // 10: protobuf.Remote
	(*RepositoryStatus)(nil),            // 11: protobuf.RepositoryStatus
	(*Store)(nil),                       // 12: protobuf.Store
	(*Event_EvalStarted)(nil),           // 13: protobuf.Event.EvalStarted
	(*Event_EvalFinished)(nil),          // 14: protobuf.Event.EvalFinished
	(*Event_BuildStarted)(nil),          // 15: protobuf.Event.BuildStarted
	(*Event_BuildFinished)(nil),         // 16: protobuf.Event.BuildFinished
	(*Event_ConfirmationSubmitted)(nil), // 17: protobuf.Event.ConfirmationSubmitted
	(*Event_ConfirmationCancelled)(nil), // 18: protobuf.Event.ConfirmationCancelled
	(*Event_ConfirmationConfirmed)(nil), // 19: protobuf.Event.ConfirmationConfirmed
	(*Event_Resume)(nil),                // 20: protobuf.Event.Resume
	(*Event_Suspend)(nil),               // 21: protobuf.Event.Suspend
	(*Event_DeploymentStarted)(nil),     // 22: protobuf.Event.DeploymentStarted
	(*Event_DeploymentFinished)(nil),    // 23: protobuf.Event.DeploymentFinished
	(*Event_RebootRequired)(nil),        // 24: protobuf.Event.RebootRequired
	nil,                                 // 25: protobuf.Store.RetentionReasonsEntry
	(*wrapperspb.BoolValue)(nil),        // 26: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil),       // 27: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 28: google.protobuf.Empty
}
var file_internal_protobuf_services_proto_depIdxs = []int32{
	13, // 0: protobuf.Event.evalStartedType:type_name -> protobuf.Event.EvalStarted
	14, // 1: protobuf.Event.evalFinishedType:type_name -> protobuf.Event.EvalFinished
	15, // 2: protobuf.Event.buildStartedType:type_name -> protobuf.Event.BuildStarted
	16, // 3: protobuf.Event.buildFinishedType:type_name -> protobuf.Event.BuildFinished
	17, // 4: protobuf.Event.confirmationSubmittedType:type_name -> protobuf.Event.ConfirmationSubmitted
	18, // 5: protobuf.Event.confirmationCancelledType:type_name -> protobuf.Event.ConfirmationCancelled
	19, // 6: protobuf.Event.confirmationConfirmedType:type_name -> protobuf.Event.ConfirmationConfirmed
	20, // 7: protobuf.Event.resume:type_name -> protobuf.Event.Resume
	21, // 8: protobuf.Event.suspend:type_name -> protobuf.Event.Suspend
	22, // 9: protobuf.Event.deploymentStartedType:type_name -> protobuf.Event.DeploymentStarted
	23, // 10: protobuf.Event.deploymentFinishedType:type_name -> protobuf.Event.DeploymentFinished
	24, // 11: protobuf.Event.rebootRequired:type_name -> protobuf.Event.RebootRequired
	26, // 12: protobuf.Generation.selected_branch_is_testing:type_name -> google.protobuf.BoolValue
	27, // 13: protobuf.Generation.eval_started_at:type_name -> google.protobuf.Timestamp
	27, // 14: protobuf.Generation.eval_ended_at:type_name -> google.protobuf.Timestamp
	27, // 15: protobuf.Generation.build_started_at:type_name -> google.protobuf.Timestamp
	27, // 16: protobuf.Generation.build_ended_at:type_name -> google.protobuf.Timestamp
	2,  // 17: protobuf.Deployment.generation:type_name -> protobuf.Generation
	27, // 18: protobuf.Deployment.started_at:type_name -> google.protobuf.Timestamp
	27, // 19: protobuf.Deployment.ended_at:type_name -> google.protobuf.Timestamp
	26, // 20: protobuf.Deployment.restart_comin:type_name -> google.protobuf.BoolValue
	27, // 21: protobuf.Deployment.created_at:type_name -> google.protobuf.Timestamp
	26, // 22: protobuf.State.need_to_reboot:type_name -> google.protobuf.BoolValue
	26, // 23: protobuf.State.is_suspended:type_name -> google.protobuf.BoolValue
	6,  // 24: protobuf.State.builder:type_name -> protobuf.Builder
	5,  // 25: protobuf.State.deployer:type_name -> protobuf.Deployer
	8,  // 26: protobuf.State.fetcher:type_name -> protobuf.Fetcher
	12, // 27: protobuf.State.store:type_name -> protobuf.Store
	7,  // 28: protobuf.State.build_confirmer:type_name -> protobuf.Confirmer
	7,  // 29: protobuf.State.deploy_confirmer:type_name -> protobuf.Confirmer
	26, // 30: protobuf.Deployer.is_deploying:type_name -> google.protobuf.BoolValue
	3,  // 31: protobuf.Deployer.deployment:type_name -> protobuf.Deployment
	2,  // 32: protobuf.Deployer.generation_to_deploy:type_name -> protobuf.Generation
	3,  // 33: protobuf.Deployer.previous_deployment:type_name -> protobuf.Deployment
	26, // 34: protobuf.Deployer.is_suspended:type_name -> google.protobuf.BoolValue
	26, // 35: protobuf.Builder.is_evaluating:type_name -> google.protobuf.BoolValue
	26, // 36: protobuf.Builder.is_building:type_name -> google.protobuf.BoolValue
	2,  // 37: protobuf.Builder.generation:type_name -> protobuf.Generation
	26, // 38: protobuf.Builder.is_suspended:type_name -> google.protobuf.BoolValue
	27, // 39: protobuf.Confirmer.autoconfirm_started_at:type_name -> google.protobuf.Timestamp
	26, // 40: protobuf.Confirmer.autoconfirm_started:type_name -> google.protobuf.BoolValue
	26, // 41: protobuf.Fetcher.is_fetching:type_name -> google.protobuf.BoolValue
	11, // 42: protobuf.Fetcher.repository_status:type_name -> protobuf.RepositoryStatus
	9,  // 43: protobuf.Remote.main:type_name -> protobuf.Branch
	9,  // 44: protobuf.Remote.testing:type_name -> protobuf.Branch
	27, // 45: protobuf.Remote.fetched_at:type_name -> google.protobuf.Timestamp
	26, // 46: protobuf.Remote.fetched:type_name -> google.protobuf.BoolValue
	26, // 47: protobuf.RepositoryStatus.selected_branch_is_testing:type_name -> google.protobuf.BoolValue
	26, // 48: protobuf.RepositoryStatus.selected_commit_signed:type_name -> google.protobuf.BoolValue
	26, // 49: protobuf.RepositoryStatus.selected_commit_should_be_signed:type_name -> google.protobuf.BoolValue
	10, // 50: protobuf.RepositoryStatus.remotes:type_name -> protobuf.Remote
	3,  // 51: protobuf.Store.deployments:type_name -> protobuf.Deployment
	2,  // 52: protobuf.Store.generations:type_name -> protobuf.Generation
	25, // 53: protobuf.Store.retention_reasons:type_name -> protobuf.Store.RetentionReasonsEntry
	2,  // 54: protobuf.Event.EvalStarted.generation:type_name -> protobuf.Generation
	2,  // 55: protobuf.Event.EvalFinished.generation:type_name -> protobuf.Generation
	2,  // 56: protobuf.Event.BuildStarted.generation:type_name -> protobuf.Generation
	2,  // 57: protobuf.Event.BuildFinished.generation:type_name -> protobuf.Generation
	3,  // 58: protobuf.Event.DeploymentStarted.deployment:type_name -> protobuf.Deployment
	3,  // 59: protobuf.Event.DeploymentFinished.deployment:type_name -> protobuf.Deployment
	3,  // 60: protobuf.Event.RebootRequired.deployment:type_name -> protobuf.Deployment
	28, // 61: protobuf.Comin.GetState:input_type -> google.protobuf.Empty
	28, // 62: protobuf.Comin.Fetch:input_type -> google.protobuf.Empty
	28, // 63: protobuf.Comin.Suspend:input_type -> google.protobuf.Empty
	28, // 64: protobuf.Comin.Resume:input_type -> google.protobuf.Empty
	1,  // 65: protobuf.Comin.Confirm:input_type -> protobuf.ConfirmRequest
	28, // 66: protobuf.Comin.Events:input_type -> google.protobuf.Empty
	28, // 67: protobuf.Comin.SwitchDeploymentLatest:input_type -> google.protobuf.Empty
	4,  // 68: protobuf.Comin.GetState:output_type -> protobuf.State
	28, // 69: protobuf.Comin.Fetch:output_type -> google.protobuf.Empty
	28, // 70: protobuf.Comin.Suspend:output_type -> google.protobuf.Empty
	28, // 71: protobuf.Comin.Resume:output_type -> google.protobuf.Empty
	28, // 72: protobuf.Comin.Confirm:output_type -> google.protobuf.Empty
	0,  // 73: protobuf.Comin.Events:output_type -> protobuf.Event
	28, // 74: protobuf.Comin.SwitchDeploymentLatest:output_type -> google.protobuf.Empty
	68, // [68:75] is the sub-list for method output_type
	61, // [61:68] is the sub-list for method input_type
	61, // [61:61] is the sub-list for extension type_name
	61, // [61:61] is the sub-list for extension extendee
	0,  // [0:61] is the sub-list for field type_name
}

func init() { file_internal_protobuf_services_proto_init() }
func file_internal_protobuf_services_proto_init() {
	if File_internal_protobuf_services_proto != nil {
		return
	}
	file_internal_protobuf_services_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_EvalStartedType)(nil),
		(*Event_EvalFinishedType)(nil),
		(*Event_BuildStartedType)(nil),
		(*Event_BuildFinishedType)(nil),
		(*Event_ConfirmationSubmittedType)(nil),
		(*Event_ConfirmationCancelledType)(nil),
		(*Event_ConfirmationConfirmedType)(nil),
		(*Event_Resume_)(nil),
		(*Event_Suspend_)(nil),
		(*Event_DeploymentStartedType)(nil),
		(*Event_DeploymentFinishedType)(nil),
		(*Event_RebootRequired_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protobuf_services_proto_rawDesc), len(file_internal_protobuf_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protobuf_services_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_services_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_services_proto_msgTypes,
	}.Build()
	File_internal_protobuf_services_proto = out.File
	file_internal_protobuf_services_proto_goTypes = nil
	file_internal_protobuf_services_proto_depIdxs = nil
}
