// To generate Go code, from the repository root directory, run:
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative internal/protobuf/services.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/protobuf/services.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// We consider each created genration is legit to be deployed: hard
// reset is ensured at RepositoryStatus creation.
type Generation struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Uuid                    string                 `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	FlakeUrl                string                 `protobuf:"bytes,2,opt,name=flake_url,json=flakeUrl" json:"flake_url,omitempty"`
	Hostname                string                 `protobuf:"bytes,3,opt,name=hostname" json:"hostname,omitempty"`
	SelectedRemoteUrl       string                 `protobuf:"bytes,4,opt,name=selected_remote_url,json=selectedRemoteUrl" json:"selected_remote_url,omitempty"`
	SelectedRemoteName      string                 `protobuf:"bytes,5,opt,name=selected_remote_name,json=selectedRemoteName" json:"selected_remote_name,omitempty"`
	SelectedBranchName      string                 `protobuf:"bytes,6,opt,name=selected_branch_name,json=selectedBranchName" json:"selected_branch_name,omitempty"`
	SelectedCommitId        string                 `protobuf:"bytes,7,opt,name=selected_commit_id,json=selectedCommitId" json:"selected_commit_id,omitempty"`
	SelectedCommitMsg       string                 `protobuf:"bytes,8,opt,name=selected_commit_msg,json=selectedCommitMsg" json:"selected_commit_msg,omitempty"`
	SelectedBranchIsTesting *wrapperspb.BoolValue  `protobuf:"bytes,9,opt,name=selected_branch_is_testing,json=selectedBranchIsTesting" json:"selected_branch_is_testing,omitempty"`
	MainCommitId            string                 `protobuf:"bytes,10,opt,name=main_commit_id,json=mainCommitId" json:"main_commit_id,omitempty"`
	MainRemoteName          string                 `protobuf:"bytes,11,opt,name=main_remote_name,json=mainRemoteName" json:"main_remote_name,omitempty"`
	MainBranchName          string                 `protobuf:"bytes,12,opt,name=main_branch_name,json=mainBranchName" json:"main_branch_name,omitempty"`
	EvalStatus              string                 `protobuf:"bytes,13,opt,name=eval_status,json=evalStatus" json:"eval_status,omitempty"`
	EvalStartedAt           *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=eval_started_at,json=evalStartedAt" json:"eval_started_at,omitempty"`
	EvalEndedAt             *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=eval_ended_at,json=evalEndedAt" json:"eval_ended_at,omitempty"`
	EvalErr                 string                 `protobuf:"bytes,16,opt,name=eval_err,json=evalErr" json:"eval_err,omitempty"`
	OutPath                 string                 `protobuf:"bytes,17,opt,name=out_path,json=outPath" json:"out_path,omitempty"`
	DrvPath                 string                 `protobuf:"bytes,18,opt,name=drv_path,json=drvPath" json:"drv_path,omitempty"`
	MachineId               string                 `protobuf:"bytes,19,opt,name=machine_id,json=machineId" json:"machine_id,omitempty"`
	BuildStatus             string                 `protobuf:"bytes,20,opt,name=build_status,json=buildStatus" json:"build_status,omitempty"`
	BuildStartedAt          *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=build_started_at,json=buildStartedAt" json:"build_started_at,omitempty"`
	BuildEndedAt            *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=build_ended_at,json=buildEndedAt" json:"build_ended_at,omitempty"`
	BuildErr                string                 `protobuf:"bytes,23,opt,name=build_err,json=buildErr" json:"build_err,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Generation) Reset() {
	*x = Generation{}
	mi := &file_internal_protobuf_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation) ProtoMessage() {}

func (x *Generation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation.ProtoReflect.Descriptor instead.
func (*Generation) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{0}
}

func (x *Generation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Generation) GetFlakeUrl() string {
	if x != nil {
		return x.FlakeUrl
	}
	return ""
}

func (x *Generation) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Generation) GetSelectedRemoteUrl() string {
	if x != nil {
		return x.SelectedRemoteUrl
	}
	return ""
}

func (x *Generation) GetSelectedRemoteName() string {
	if x != nil {
		return x.SelectedRemoteName
	}
	return ""
}

func (x *Generation) GetSelectedBranchName() string {
	if x != nil {
		return x.SelectedBranchName
	}
	return ""
}

func (x *Generation) GetSelectedCommitId() string {
	if x != nil {
		return x.SelectedCommitId
	}
	return ""
}

func (x *Generation) GetSelectedCommitMsg() string {
	if x != nil {
		return x.SelectedCommitMsg
	}
	return ""
}

func (x *Generation) GetSelectedBranchIsTesting() *wrapperspb.BoolValue {
	if x != nil {
		return x.SelectedBranchIsTesting
	}
	return nil
}

func (x *Generation) GetMainCommitId() string {
	if x != nil {
		return x.MainCommitId
	}
	return ""
}

func (x *Generation) GetMainRemoteName() string {
	if x != nil {
		return x.MainRemoteName
	}
	return ""
}

func (x *Generation) GetMainBranchName() string {
	if x != nil {
		return x.MainBranchName
	}
	return ""
}

func (x *Generation) GetEvalStatus() string {
	if x != nil {
		return x.EvalStatus
	}
	return ""
}

func (x *Generation) GetEvalStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvalStartedAt
	}
	return nil
}

func (x *Generation) GetEvalEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvalEndedAt
	}
	return nil
}

func (x *Generation) GetEvalErr() string {
	if x != nil {
		return x.EvalErr
	}
	return ""
}

func (x *Generation) GetOutPath() string {
	if x != nil {
		return x.OutPath
	}
	return ""
}

func (x *Generation) GetDrvPath() string {
	if x != nil {
		return x.DrvPath
	}
	return ""
}

func (x *Generation) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Generation) GetBuildStatus() string {
	if x != nil {
		return x.BuildStatus
	}
	return ""
}

func (x *Generation) GetBuildStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BuildStartedAt
	}
	return nil
}

func (x *Generation) GetBuildEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BuildEndedAt
	}
	return nil
}

func (x *Generation) GetBuildErr() string {
	if x != nil {
		return x.BuildErr
	}
	return ""
}

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Generation    *Generation            `protobuf:"bytes,2,opt,name=generation" json:"generation,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt" json:"ended_at,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg" json:"error_msg,omitempty"`
	RestartComin  *wrapperspb.BoolValue  `protobuf:"bytes,6,opt,name=restart_comin,json=restartComin" json:"restart_comin,omitempty"`
	ProfilePath   string                 `protobuf:"bytes,7,opt,name=profile_path,json=profilePath" json:"profile_path,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
	Operation     string                 `protobuf:"bytes,9,opt,name=operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_internal_protobuf_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{1}
}

func (x *Deployment) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Deployment) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *Deployment) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Deployment) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Deployment) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *Deployment) GetRestartComin() *wrapperspb.BoolValue {
	if x != nil {
		return x.RestartComin
	}
	return nil
}

func (x *Deployment) GetProfilePath() string {
	if x != nil {
		return x.ProfilePath
	}
	return ""
}

func (x *Deployment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Deployment) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeedToReboot  *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=need_to_reboot,json=needToReboot" json:"need_to_reboot,omitempty"`
	IsSuspended   *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=is_suspended,json=isSuspended" json:"is_suspended,omitempty"`
	Builder       *Builder               `protobuf:"bytes,3,opt,name=builder" json:"builder,omitempty"`
	Deployer      *Deployer              `protobuf:"bytes,4,opt,name=deployer" json:"deployer,omitempty"`
	Fetcher       *Fetcher               `protobuf:"bytes,5,opt,name=fetcher" json:"fetcher,omitempty"`
	Store         *Store                 `protobuf:"bytes,6,opt,name=store" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_internal_protobuf_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{2}
}

func (x *State) GetNeedToReboot() *wrapperspb.BoolValue {
	if x != nil {
		return x.NeedToReboot
	}
	return nil
}

func (x *State) GetIsSuspended() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsSuspended
	}
	return nil
}

func (x *State) GetBuilder() *Builder {
	if x != nil {
		return x.Builder
	}
	return nil
}

func (x *State) GetDeployer() *Deployer {
	if x != nil {
		return x.Deployer
	}
	return nil
}

func (x *State) GetFetcher() *Fetcher {
	if x != nil {
		return x.Fetcher
	}
	return nil
}

func (x *State) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

type Deployer struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IsDeploying        *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=is_deploying,json=isDeploying" json:"is_deploying,omitempty"`
	Deployment         *Deployment            `protobuf:"bytes,2,opt,name=deployment" json:"deployment,omitempty"`
	GenerationToDeploy *Generation            `protobuf:"bytes,3,opt,name=generation_to_deploy,json=generationToDeploy" json:"generation_to_deploy,omitempty"`
	PreviousDeployment *Deployment            `protobuf:"bytes,4,opt,name=previous_deployment,json=previousDeployment" json:"previous_deployment,omitempty"`
	IsSuspended        *wrapperspb.BoolValue  `protobuf:"bytes,5,opt,name=is_suspended,json=isSuspended" json:"is_suspended,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Deployer) Reset() {
	*x = Deployer{}
	mi := &file_internal_protobuf_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployer) ProtoMessage() {}

func (x *Deployer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployer.ProtoReflect.Descriptor instead.
func (*Deployer) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{3}
}

func (x *Deployer) GetIsDeploying() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsDeploying
	}
	return nil
}

func (x *Deployer) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *Deployer) GetGenerationToDeploy() *Generation {
	if x != nil {
		return x.GenerationToDeploy
	}
	return nil
}

func (x *Deployer) GetPreviousDeployment() *Deployment {
	if x != nil {
		return x.PreviousDeployment
	}
	return nil
}

func (x *Deployer) GetIsSuspended() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsSuspended
	}
	return nil
}

type Builder struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsEvaluating   *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=is_evaluating,json=isEvaluating" json:"is_evaluating,omitempty"`
	IsBuilding     *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=is_building,json=isBuilding" json:"is_building,omitempty"`
	Generation     *Generation            `protobuf:"bytes,3,opt,name=generation" json:"generation,omitempty"`
	GenerationUuid string                 `protobuf:"bytes,4,opt,name=generation_uuid,json=generationUuid" json:"generation_uuid,omitempty"`
	IsSuspended    *wrapperspb.BoolValue  `protobuf:"bytes,5,opt,name=is_suspended,json=isSuspended" json:"is_suspended,omitempty"`
	Hostname       string                 `protobuf:"bytes,6,opt,name=hostname" json:"hostname,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Builder) Reset() {
	*x = Builder{}
	mi := &file_internal_protobuf_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Builder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Builder) ProtoMessage() {}

func (x *Builder) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Builder.ProtoReflect.Descriptor instead.
func (*Builder) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{4}
}

func (x *Builder) GetIsEvaluating() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsEvaluating
	}
	return nil
}

func (x *Builder) GetIsBuilding() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsBuilding
	}
	return nil
}

func (x *Builder) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *Builder) GetGenerationUuid() string {
	if x != nil {
		return x.GenerationUuid
	}
	return ""
}

func (x *Builder) GetIsSuspended() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsSuspended
	}
	return nil
}

func (x *Builder) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type Fetcher struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsFetching       *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=is_fetching,json=isFetching" json:"is_fetching,omitempty"`
	RepositoryStatus *RepositoryStatus      `protobuf:"bytes,2,opt,name=repository_status,json=repositoryStatus" json:"repository_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Fetcher) Reset() {
	*x = Fetcher{}
	mi := &file_internal_protobuf_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fetcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fetcher) ProtoMessage() {}

func (x *Fetcher) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fetcher.ProtoReflect.Descriptor instead.
func (*Fetcher) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{5}
}

func (x *Fetcher) GetIsFetching() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsFetching
	}
	return nil
}

func (x *Fetcher) GetRepositoryStatus() *RepositoryStatus {
	if x != nil {
		return x.RepositoryStatus
	}
	return nil
}

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CommitId      string                 `protobuf:"bytes,2,opt,name=commit_id,json=commitId" json:"commit_id,omitempty"`
	CommitMsg     string                 `protobuf:"bytes,3,opt,name=commit_msg,json=commitMsg" json:"commit_msg,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg" json:"error_msg,omitempty"`
	OnTopOf       string                 `protobuf:"bytes,5,opt,name=on_top_of,json=onTopOf" json:"on_top_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_internal_protobuf_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{6}
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *Branch) GetCommitMsg() string {
	if x != nil {
		return x.CommitMsg
	}
	return ""
}

func (x *Branch) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *Branch) GetOnTopOf() string {
	if x != nil {
		return x.OnTopOf
	}
	return ""
}

type Remote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	FetchErrorMsg string                 `protobuf:"bytes,3,opt,name=fetch_error_msg,json=fetchErrorMsg" json:"fetch_error_msg,omitempty"`
	Main          *Branch                `protobuf:"bytes,4,opt,name=main" json:"main,omitempty"`
	Testing       *Branch                `protobuf:"bytes,5,opt,name=testing" json:"testing,omitempty"`
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=fetched_at,json=fetchedAt" json:"fetched_at,omitempty"`
	Fetched       *wrapperspb.BoolValue  `protobuf:"bytes,7,opt,name=fetched" json:"fetched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Remote) Reset() {
	*x = Remote{}
	mi := &file_internal_protobuf_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remote) ProtoMessage() {}

func (x *Remote) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remote.ProtoReflect.Descriptor instead.
func (*Remote) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{7}
}

func (x *Remote) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Remote) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Remote) GetFetchErrorMsg() string {
	if x != nil {
		return x.FetchErrorMsg
	}
	return ""
}

func (x *Remote) GetMain() *Branch {
	if x != nil {
		return x.Main
	}
	return nil
}

func (x *Remote) GetTesting() *Branch {
	if x != nil {
		return x.Testing
	}
	return nil
}

func (x *Remote) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

func (x *Remote) GetFetched() *wrapperspb.BoolValue {
	if x != nil {
		return x.Fetched
	}
	return nil
}

type RepositoryStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This is the deployed Main commit ID. It is used to ensure fast forward
	SelectedCommitId        string                `protobuf:"bytes,1,opt,name=selected_commit_id,json=selectedCommitId" json:"selected_commit_id,omitempty"`
	SelectedCommitMsg       string                `protobuf:"bytes,2,opt,name=selected_commit_msg,json=selectedCommitMsg" json:"selected_commit_msg,omitempty"`
	SelectedRemoteName      string                `protobuf:"bytes,3,opt,name=selected_remote_name,json=selectedRemoteName" json:"selected_remote_name,omitempty"`
	SelectedBranchName      string                `protobuf:"bytes,4,opt,name=selected_branch_name,json=selectedBranchName" json:"selected_branch_name,omitempty"`
	SelectedBranchIsTesting *wrapperspb.BoolValue `protobuf:"bytes,5,opt,name=selected_branch_is_testing,json=selectedBranchIsTesting" json:"selected_branch_is_testing,omitempty"`
	SelectedCommitSigned    *wrapperspb.BoolValue `protobuf:"bytes,6,opt,name=selected_commit_signed,json=selectedCommitSigned" json:"selected_commit_signed,omitempty"`
	SelectedCommitSignedBy  string                `protobuf:"bytes,7,opt,name=selected_commit_signed_by,json=selectedCommitSignedBy" json:"selected_commit_signed_by,omitempty"`
	// True if public keys were available when the commit has been checked out
	SelectedCommitShouldBeSigned *wrapperspb.BoolValue `protobuf:"bytes,8,opt,name=selected_commit_should_be_signed,json=selectedCommitShouldBeSigned" json:"selected_commit_should_be_signed,omitempty"`
	MainCommitId                 string                `protobuf:"bytes,9,opt,name=main_commit_id,json=mainCommitId" json:"main_commit_id,omitempty"`
	MainRemoteName               string                `protobuf:"bytes,10,opt,name=main_remote_name,json=mainRemoteName" json:"main_remote_name,omitempty"`
	MainBranchName               string                `protobuf:"bytes,11,opt,name=main_branch_name,json=mainBranchName" json:"main_branch_name,omitempty"`
	Remotes                      []*Remote             `protobuf:"bytes,12,rep,name=remotes" json:"remotes,omitempty"`
	ErrorMsg                     string                `protobuf:"bytes,13,opt,name=error_msg,json=errorMsg" json:"error_msg,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RepositoryStatus) Reset() {
	*x = RepositoryStatus{}
	mi := &file_internal_protobuf_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryStatus) ProtoMessage() {}

func (x *RepositoryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryStatus.ProtoReflect.Descriptor instead.
func (*RepositoryStatus) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{8}
}

func (x *RepositoryStatus) GetSelectedCommitId() string {
	if x != nil {
		return x.SelectedCommitId
	}
	return ""
}

func (x *RepositoryStatus) GetSelectedCommitMsg() string {
	if x != nil {
		return x.SelectedCommitMsg
	}
	return ""
}

func (x *RepositoryStatus) GetSelectedRemoteName() string {
	if x != nil {
		return x.SelectedRemoteName
	}
	return ""
}

func (x *RepositoryStatus) GetSelectedBranchName() string {
	if x != nil {
		return x.SelectedBranchName
	}
	return ""
}

func (x *RepositoryStatus) GetSelectedBranchIsTesting() *wrapperspb.BoolValue {
	if x != nil {
		return x.SelectedBranchIsTesting
	}
	return nil
}

func (x *RepositoryStatus) GetSelectedCommitSigned() *wrapperspb.BoolValue {
	if x != nil {
		return x.SelectedCommitSigned
	}
	return nil
}

func (x *RepositoryStatus) GetSelectedCommitSignedBy() string {
	if x != nil {
		return x.SelectedCommitSignedBy
	}
	return ""
}

func (x *RepositoryStatus) GetSelectedCommitShouldBeSigned() *wrapperspb.BoolValue {
	if x != nil {
		return x.SelectedCommitShouldBeSigned
	}
	return nil
}

func (x *RepositoryStatus) GetMainCommitId() string {
	if x != nil {
		return x.MainCommitId
	}
	return ""
}

func (x *RepositoryStatus) GetMainRemoteName() string {
	if x != nil {
		return x.MainRemoteName
	}
	return ""
}

func (x *RepositoryStatus) GetMainBranchName() string {
	if x != nil {
		return x.MainBranchName
	}
	return ""
}

func (x *RepositoryStatus) GetRemotes() []*Remote {
	if x != nil {
		return x.Remotes
	}
	return nil
}

func (x *RepositoryStatus) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type Store struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments" json:"deployments,omitempty"`
	Generations   []*Generation          `protobuf:"bytes,2,rep,name=generations" json:"generations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_internal_protobuf_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_services_proto_rawDescGZIP(), []int{9}
}

func (x *Store) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *Store) GetGenerations() []*Generation {
	if x != nil {
		return x.Generations
	}
	return nil
}

var File_internal_protobuf_services_proto protoreflect.FileDescriptor

const file_internal_protobuf_services_proto_rawDesc = "" +
	"\n" +
	" internal/protobuf/services.proto\x12\bprotobuf\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xfb\a\n" +
	"\n" +
	"Generation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1b\n" +
	"\tflake_url\x18\x02 \x01(\tR\bflakeUrl\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12.\n" +
	"\x13selected_remote_url\x18\x04 \x01(\tR\x11selectedRemoteUrl\x120\n" +
	"\x14selected_remote_name\x18\x05 \x01(\tR\x12selectedRemoteName\x120\n" +
	"\x14selected_branch_name\x18\x06 \x01(\tR\x12selectedBranchName\x12,\n" +
	"\x12selected_commit_id\x18\a \x01(\tR\x10selectedCommitId\x12.\n" +
	"\x13selected_commit_msg\x18\b \x01(\tR\x11selectedCommitMsg\x12W\n" +
	"\x1aselected_branch_is_testing\x18\t \x01(\v2\x1a.google.protobuf.BoolValueR\x17selectedBranchIsTesting\x12$\n" +
	"\x0emain_commit_id\x18\n" +
	" \x01(\tR\fmainCommitId\x12(\n" +
	"\x10main_remote_name\x18\v \x01(\tR\x0emainRemoteName\x12(\n" +
	"\x10main_branch_name\x18\f \x01(\tR\x0emainBranchName\x12\x1f\n" +
	"\veval_status\x18\r \x01(\tR\n" +
	"evalStatus\x12B\n" +
	"\x0feval_started_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\revalStartedAt\x12>\n" +
	"\reval_ended_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vevalEndedAt\x12\x19\n" +
	"\beval_err\x18\x10 \x01(\tR\aevalErr\x12\x19\n" +
	"\bout_path\x18\x11 \x01(\tR\aoutPath\x12\x19\n" +
	"\bdrv_path\x18\x12 \x01(\tR\adrvPath\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x13 \x01(\tR\tmachineId\x12!\n" +
	"\fbuild_status\x18\x14 \x01(\tR\vbuildStatus\x12D\n" +
	"\x10build_started_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\x0ebuildStartedAt\x12@\n" +
	"\x0ebuild_ended_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\fbuildEndedAt\x12\x1b\n" +
	"\tbuild_err\x18\x17 \x01(\tR\bbuildErr\"\xff\x02\n" +
	"\n" +
	"Deployment\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x124\n" +
	"\n" +
	"generation\x18\x02 \x01(\v2\x14.protobuf.GenerationR\n" +
	"generation\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x12?\n" +
	"\rrestart_comin\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\frestartComin\x12!\n" +
	"\fprofile_path\x18\a \x01(\tR\vprofilePath\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1c\n" +
	"\toperation\x18\t \x01(\tR\toperation\"\xb9\x02\n" +
	"\x05State\x12@\n" +
	"\x0eneed_to_reboot\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\fneedToReboot\x12=\n" +
	"\fis_suspended\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\visSuspended\x12+\n" +
	"\abuilder\x18\x03 \x01(\v2\x11.protobuf.BuilderR\abuilder\x12.\n" +
	"\bdeployer\x18\x04 \x01(\v2\x12.protobuf.DeployerR\bdeployer\x12+\n" +
	"\afetcher\x18\x05 \x01(\v2\x11.protobuf.FetcherR\afetcher\x12%\n" +
	"\x05store\x18\x06 \x01(\v2\x0f.protobuf.StoreR\x05store\"\xcd\x02\n" +
	"\bDeployer\x12=\n" +
	"\fis_deploying\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\visDeploying\x124\n" +
	"\n" +
	"deployment\x18\x02 \x01(\v2\x14.protobuf.DeploymentR\n" +
	"deployment\x12F\n" +
	"\x14generation_to_deploy\x18\x03 \x01(\v2\x14.protobuf.GenerationR\x12generationToDeploy\x12E\n" +
	"\x13previous_deployment\x18\x04 \x01(\v2\x14.protobuf.DeploymentR\x12previousDeployment\x12=\n" +
	"\fis_suspended\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\visSuspended\"\xc1\x02\n" +
	"\aBuilder\x12?\n" +
	"\ris_evaluating\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\fisEvaluating\x12;\n" +
	"\vis_building\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"isBuilding\x124\n" +
	"\n" +
	"generation\x18\x03 \x01(\v2\x14.protobuf.GenerationR\n" +
	"generation\x12'\n" +
	"\x0fgeneration_uuid\x18\x04 \x01(\tR\x0egenerationUuid\x12=\n" +
	"\fis_suspended\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\visSuspended\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\"\x8f\x01\n" +
	"\aFetcher\x12;\n" +
	"\vis_fetching\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"isFetching\x12G\n" +
	"\x11repository_status\x18\x02 \x01(\v2\x1a.protobuf.RepositoryStatusR\x10repositoryStatus\"\x91\x01\n" +
	"\x06Branch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tcommit_id\x18\x02 \x01(\tR\bcommitId\x12\x1d\n" +
	"\n" +
	"commit_msg\x18\x03 \x01(\tR\tcommitMsg\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\x12\x1a\n" +
	"\ton_top_of\x18\x05 \x01(\tR\aonTopOf\"\x99\x02\n" +
	"\x06Remote\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12&\n" +
	"\x0ffetch_error_msg\x18\x03 \x01(\tR\rfetchErrorMsg\x12$\n" +
	"\x04main\x18\x04 \x01(\v2\x10.protobuf.BranchR\x04main\x12*\n" +
	"\atesting\x18\x05 \x01(\v2\x10.protobuf.BranchR\atesting\x129\n" +
	"\n" +
	"fetched_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\x124\n" +
	"\afetched\x18\a \x01(\v2\x1a.google.protobuf.BoolValueR\afetched\"\xe1\x05\n" +
	"\x10RepositoryStatus\x12,\n" +
	"\x12selected_commit_id\x18\x01 \x01(\tR\x10selectedCommitId\x12.\n" +
	"\x13selected_commit_msg\x18\x02 \x01(\tR\x11selectedCommitMsg\x120\n" +
	"\x14selected_remote_name\x18\x03 \x01(\tR\x12selectedRemoteName\x120\n" +
	"\x14selected_branch_name\x18\x04 \x01(\tR\x12selectedBranchName\x12W\n" +
	"\x1aselected_branch_is_testing\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\x17selectedBranchIsTesting\x12P\n" +
	"\x16selected_commit_signed\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\x14selectedCommitSigned\x129\n" +
	"\x19selected_commit_signed_by\x18\a \x01(\tR\x16selectedCommitSignedBy\x12b\n" +
	" selected_commit_should_be_signed\x18\b \x01(\v2\x1a.google.protobuf.BoolValueR\x1cselectedCommitShouldBeSigned\x12$\n" +
	"\x0emain_commit_id\x18\t \x01(\tR\fmainCommitId\x12(\n" +
	"\x10main_remote_name\x18\n" +
	" \x01(\tR\x0emainRemoteName\x12(\n" +
	"\x10main_branch_name\x18\v \x01(\tR\x0emainBranchName\x12*\n" +
	"\aremotes\x18\f \x03(\v2\x10.protobuf.RemoteR\aremotes\x12\x1b\n" +
	"\terror_msg\x18\r \x01(\tR\berrorMsg\"w\n" +
	"\x05Store\x126\n" +
	"\vdeployments\x18\x01 \x03(\v2\x14.protobuf.DeploymentR\vdeployments\x126\n" +
	"\vgenerations\x18\x02 \x03(\v2\x14.protobuf.GenerationR\vgenerations2\xf2\x01\n" +
	"\x05Comin\x125\n" +
	"\bGetState\x12\x16.google.protobuf.Empty\x1a\x0f.protobuf.State\"\x00\x129\n" +
	"\x05Fetch\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12;\n" +
	"\aSuspend\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12:\n" +
	"\x06Resume\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B/Z(github.com/nlewo/comin/internal/protobuf\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_internal_protobuf_services_proto_rawDescOnce sync.Once
	file_internal_protobuf_services_proto_rawDescData []byte
)

func file_internal_protobuf_services_proto_rawDescGZIP() []byte {
	file_internal_protobuf_services_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protobuf_services_proto_rawDesc), len(file_internal_protobuf_services_proto_rawDesc)))
	})
	return file_internal_protobuf_services_proto_rawDescData
}

var file_internal_protobuf_services_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_protobuf_services_proto_goTypes = []any{
	(*Generation)(nil),            // 0: protobuf.Generation
	(*Deployment)(nil),            // 1: protobuf.Deployment
	(*State)(nil),                 // 2: protobuf.State
	(*Deployer)(nil),              // 3: protobuf.Deployer
	(*Builder)(nil),               // 4: protobuf.Builder
	(*Fetcher)(nil),               // 5: protobuf.Fetcher
	(*Branch)(nil),                // 6: protobuf.Branch
	(*Remote)(nil),                // 7: protobuf.Remote
	(*RepositoryStatus)(nil),      // 8: protobuf.RepositoryStatus
	(*Store)(nil),                 // 9: protobuf.Store
	(*wrapperspb.BoolValue)(nil),  // 10: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_internal_protobuf_services_proto_depIdxs = []int32{
	10, // 0: protobuf.Generation.selected_branch_is_testing:type_name -> google.protobuf.BoolValue
	11, // 1: protobuf.Generation.eval_started_at:type_name -> google.protobuf.Timestamp
	11, // 2: protobuf.Generation.eval_ended_at:type_name -> google.protobuf.Timestamp
	11, // 3: protobuf.Generation.build_started_at:type_name -> google.protobuf.Timestamp
	11, // 4: protobuf.Generation.build_ended_at:type_name -> google.protobuf.Timestamp
	0,  // 5: protobuf.Deployment.generation:type_name -> protobuf.Generation
	11, // 6: protobuf.Deployment.started_at:type_name -> google.protobuf.Timestamp
	11, // 7: protobuf.Deployment.ended_at:type_name -> google.protobuf.Timestamp
	10, // 8: protobuf.Deployment.restart_comin:type_name -> google.protobuf.BoolValue
	10, // 9: protobuf.State.need_to_reboot:type_name -> google.protobuf.BoolValue
	10, // 10: protobuf.State.is_suspended:type_name -> google.protobuf.BoolValue
	4,  // 11: protobuf.State.builder:type_name -> protobuf.Builder
	3,  // 12: protobuf.State.deployer:type_name -> protobuf.Deployer
	5,  // 13: protobuf.State.fetcher:type_name -> protobuf.Fetcher
	9,  // 14: protobuf.State.store:type_name -> protobuf.Store
	10, // 15: protobuf.Deployer.is_deploying:type_name -> google.protobuf.BoolValue
	1,  // 16: protobuf.Deployer.deployment:type_name -> protobuf.Deployment
	0,  // 17: protobuf.Deployer.generation_to_deploy:type_name -> protobuf.Generation
	1,  // 18: protobuf.Deployer.previous_deployment:type_name -> protobuf.Deployment
	10, // 19: protobuf.Deployer.is_suspended:type_name -> google.protobuf.BoolValue
	10, // 20: protobuf.Builder.is_evaluating:type_name -> google.protobuf.BoolValue
	10, // 21: protobuf.Builder.is_building:type_name -> google.protobuf.BoolValue
	0,  // 22: protobuf.Builder.generation:type_name -> protobuf.Generation
	10, // 23: protobuf.Builder.is_suspended:type_name -> google.protobuf.BoolValue
	10, // 24: protobuf.Fetcher.is_fetching:type_name -> google.protobuf.BoolValue
	8,  // 25: protobuf.Fetcher.repository_status:type_name -> protobuf.RepositoryStatus
	6,  // 26: protobuf.Remote.main:type_name -> protobuf.Branch
	6,  // 27: protobuf.Remote.testing:type_name -> protobuf.Branch
	11, // 28: protobuf.Remote.fetched_at:type_name -> google.protobuf.Timestamp
	10, // 29: protobuf.Remote.fetched:type_name -> google.protobuf.BoolValue
	10, // 30: protobuf.RepositoryStatus.selected_branch_is_testing:type_name -> google.protobuf.BoolValue
	10, // 31: protobuf.RepositoryStatus.selected_commit_signed:type_name -> google.protobuf.BoolValue
	10, // 32: protobuf.RepositoryStatus.selected_commit_should_be_signed:type_name -> google.protobuf.BoolValue
	7,  // 33: protobuf.RepositoryStatus.remotes:type_name -> protobuf.Remote
	1,  // 34: protobuf.Store.deployments:type_name -> protobuf.Deployment
	0,  // 35: protobuf.Store.generations:type_name -> protobuf.Generation
	12, // 36: protobuf.Comin.GetState:input_type -> google.protobuf.Empty
	12, // 37: protobuf.Comin.Fetch:input_type -> google.protobuf.Empty
	12, // 38: protobuf.Comin.Suspend:input_type -> google.protobuf.Empty
	12, // 39: protobuf.Comin.Resume:input_type -> google.protobuf.Empty
	2,  // 40: protobuf.Comin.GetState:output_type -> protobuf.State
	12, // 41: protobuf.Comin.Fetch:output_type -> google.protobuf.Empty
	12, // 42: protobuf.Comin.Suspend:output_type -> google.protobuf.Empty
	12, // 43: protobuf.Comin.Resume:output_type -> google.protobuf.Empty
	40, // [40:44] is the sub-list for method output_type
	36, // [36:40] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_internal_protobuf_services_proto_init() }
func file_internal_protobuf_services_proto_init() {
	if File_internal_protobuf_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protobuf_services_proto_rawDesc), len(file_internal_protobuf_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protobuf_services_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_services_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_services_proto_msgTypes,
	}.Build()
	File_internal_protobuf_services_proto = out.File
	file_internal_protobuf_services_proto_goTypes = nil
	file_internal_protobuf_services_proto_depIdxs = nil
}
